BlogGame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('account.urls', namespace='account')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'blog.views.not_found'

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('article', views.article, name='article'),
    path('article/<int:pk>', views.article_detail, name='article_detail'),
    path('reports', views.report_list, name='report_list'),
    path('report<int:pk>', views.report, name='report_detail'),
    path('note_list', views.list_note, name='note_list'),
    path('detail_note/<int:pk>', views.detail_note, name='detail_note'),
    path('list_phto', views.photo_list, name='photo_list'),
    path('detail_photo/<int:pk>', views.detail_photo, name='detail_photo'),
    path('search', views.search, name='search'),
    path('category/<str:slug>', views.category, name='category'),
    path('about', views.about, name='about'),
    path('contacat', views.contact_us, name='contact_us'),
    path('video/<int:pk>', views.video_detail, name='video_detail'),
    path('video', views.video_list, name='video_list'),
    path('submitted', views.submitted_list, name='submitted_list'),
    path('submitted/<int:pk>', views.submitted_detail, name='submitted_detail'),


]

blog/models.py
from django.db import models
from django.urls import reverse
from django_resized import ResizedImageField


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=25, verbose_name="نام")
    slug = models.SlugField(max_length=50, unique=True, verbose_name="اسلاگ")

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها '

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', args=[self.slug])


class Post(models.Model):
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE, blank=True, null=True,
                                 verbose_name="دسته بندی")
    title = models.CharField(max_length=150, verbose_name='عنوان')
    slug = models.SlugField(max_length=50, verbose_name='اسلاگ')
    content = models.TextField(verbose_name='محتوا')
    full_content = models.TextField(verbose_name='محتوا کامل ')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت')
    image = ResizedImageField(upload_to='media', verbose_name='تصویر', size=[500, 500])
    hot = models.BooleanField(default=False, verbose_name='تیتر خبر ها ')

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[self.id])

    class Meta:
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title


class Note(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان')
    note = models.TextField(verbose_name='متن')
    likes = models.IntegerField(default=0, verbose_name='لایک ها ')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت')

    def get_absolute_url(self):
        return reverse('blog:detail_note', args=[self.id])

    class Meta:
        verbose_name = 'یادداشت'
        verbose_name_plural = 'یادداشت ها'

    def __str__(self):
        return self.title


class Photo(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان')
    image1 = ResizedImageField(upload_to='media', verbose_name='تصویر1', size=[500, 500])
    image2 = ResizedImageField(upload_to='media', verbose_name='تصویر2', size=[500, 500], blank=True, null=True)
    image3 = ResizedImageField(upload_to='media', verbose_name='تصویر3', size=[500, 500], blank=True, null=True)
    image4 = ResizedImageField(upload_to='media', verbose_name='تصویر4', size=[500, 500], blank=True, null=True)
    image5 = ResizedImageField(upload_to='media', verbose_name='تصویر5', size=[500, 500], blank=True, null=True)
    content = models.TextField(verbose_name='متن تصویر')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'تصویری '
        verbose_name_plural = 'تصویری ها'

    def get_absolute_url(self):
        return reverse('blog:detail_photo', args=[self.id])


class Report(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان')
    content = models.TextField(verbose_name='متن')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')

    def get_absolute_url(self):
        return reverse('blog:report_detail', args=[self.id])

    class Meta:
        verbose_name = 'گزارش'
        verbose_name_plural = 'گزارش ها'

    def __str__(self):
        return self.title


class Resume(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان')
    image1 = ResizedImageField(upload_to='media', verbose_name='تصویر1')
    image2 = ResizedImageField(upload_to='media', verbose_name='تصویر 2', blank=True, null=True)


class Video(models.Model):
    category = models.ForeignKey(Category, related_name='videos', on_delete=models.CASCADE, blank=True, null=True,
                                 verbose_name='دسته بندی ')
    title = models.CharField(max_length=250, verbose_name='عنوان')
    content = models.TextField(verbose_name='متن')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')
    video = models.FileField(upload_to='media', verbose_name='فیلم')
    image = ResizedImageField(upload_to='media', verbose_name='تصویر', blank=True, null=True, )

    def get_absolute_url(self):
        return reverse('blog:video_detail', args=[self.id])

    class Meta:
        verbose_name = 'ویدیو'
        verbose_name_plural = 'ویدیو ها'

    def __str__(self):
        return self.title


class Advertising(models.Model):
    title = models.CharField(max_length=250, verbose_name='عنوان')
    video = models.FileField(upload_to='Advertising/%Y/%m/%d', verbose_name='تبلیغ')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار ')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ تمدید ')

    class Meta:
        verbose_name = 'تبلیغ'
        verbose_name_plural = 'تبلیغات'

    def __str__(self):
        return self.title


class Submitted(models.Model):
    sender = models.CharField(max_length=50, verbose_name='ارسال کننده')
    title = models.CharField(max_length=250, verbose_name='عنوان ')
    video = models.FileField(upload_to='Submitted', verbose_name='ویدیو', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال', )
    image = models.ImageField(upload_to='Submitted', verbose_name='تصویر')
    content = models.TextField(verbose_name='محتوا')

    def get_absolute_url(self):
        return reverse('blog:submitted_detail', args=[self.id])

    class Meta:
        verbose_name = 'گفت گو'
        verbose_name_plural = 'گفت گو ها'

    def __str__(self):
        return self.title


class Comments(models.Model):
    sender = models.CharField(max_length=50, verbose_name='نویسنده')
    email = models.EmailField(max_length=254, verbose_name='ایمیل')
    content = models.TextField(verbose_name='کامنت')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name='پست', null=True,
                             blank=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name="comments", verbose_name='ویدیو', null=True
                              , blank=True)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name="comments", verbose_name='تصویری', null=True
                              , blank=True)
    allowed = models.BooleanField(default=False, verbose_name='مجوز')

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'

    def __str__(self):
        return self.sender

blog/forms.py
from django import forms

from blog.models import Comments


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['sender', 'email', 'content']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import *
from .forms import CommentForm, SearchForm, Comments
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def paginate(request, queryset, page):
    paginator = Paginator(queryset, page)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)

    return posts


def comments(request, pk, ppv, sr):
    show = ppv.comments.filter(allowed=True).order_by('-created')
    form = CommentForm(data=request.POST)
    comment = None
    if form.is_valid():
        comment = form.save(commit=False)
        if 'post' == sr:
            comment.post = ppv
        elif 'video' == sr:
            comment.video = ppv
        elif 'photo' == sr:
            comment.photo = ppv
        comment.save()
    context = [comment, form, ppv, show]
    return context


def index(request):
    categories = Category.objects.all()
    note = Note.objects.all()
    photos = Photo.objects.all()
    comment = Comments.objects.all()
    post = Post.objects.all()
    view_up = post.filter(created__lte=timezone.now())
    view_dey = view_up.last()
    hot = post.filter(hot=True).all()
    reports = Report.objects.all()
    video = Video.objects.all().order_by('-created')
    video2 = video[:2]
    advertising = Advertising.objects.all()
    submitted = Submitted.objects.all()
    context = {
        'photos': photos[:3],
        'categories': categories,
        'notes': note[:5],
        'comments': comment,
        'posts': post[:6],
        'hots': hot[:3],
        'report': reports[:5],
        'view_day': view_dey,
        'view_up': view_up[:3],
        'video': video,
        'video2': video2,
        'advertising': advertising[:2],
        'submitted': submitted[:4]

    }
    return render(request, 'blog/index.html', context)


def article(request):
    posts = Post.objects.all()
    posts = paginate(request, posts, 12)
    context = {
        'posts': posts,
        'category': category,

    }
    return render(request, 'blog/article.html', context)


def article_detail(request, pk):
    post = Post.objects.get(pk=pk)
    comment = comments(request, pk, post, 'post')
    context = {
        'comment': comment[0],
        'form': comment[1],
        'post': comment[2],
        'show': comment[3],
    }
    return render(request, 'blog/detail.html', context)


def search(request):
    if 'query' in request.GET:
        query = request
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.all().filter(title=query)
            results = paginate(request, results, 12)
    context = {
        'query': query,
        'results': results,
    }
    return render(request, 'blog/search.html', context)


def category(request, slug=None):
    category = None
    categories = Category.objects.all()
    posts = Post.objects.all()

    if slug:
        category = get_object_or_404(Category, slug=slug)
        posts = posts.filter(category=category)
        posts = paginate(request, posts, 12)

    context = {
        'category': category,
        'categories': categories,
        'posts': posts,
    }
    return render(request, 'blog/category.html', context)


def about(request):
    resume = Resume.objects.all()
    context = {
        'resume': resume
    }
    return render(request, 'blog/about.html', context)


def contact_us(request):
    return render(request, 'blog/contact_us.html', )


def list_note(request):
    notes = Note.objects.all()
    notes = paginate(request, notes, 12)
    context = {
        'notes': notes
    }
    return render(request, 'blog/note_list.html', context)


def detail_note(request, pk):
    note = get_object_or_404(Note, pk=pk)
    context = {
        'notes': note
    }
    return render(request, 'blog/detail_note.html', context)


def photo_list(request):
    photos = Photo.objects.all()
    photos = paginate(request, photos, 12)
    context = {
        'photos': photos,
    }
    return render(request, 'blog/photo_list.html', context)


def detail_photo(request, pk):
    photo = Photo.objects.get(pk=pk)
    comment = comments(request, pk, photo, 'photo')
    context = {
        'comment': comment[0],
        'form': comment[1],
        'photo': comment[2],
        'show': comment[3],
    }
    return render(request, 'blog/detail_photo.html', context)


def report_list(request):
    reports = Report.objects.all()
    reports = paginate(request, reports, 12)
    context = {
        'reports': reports
    }

    return render(request, 'blog/report_list.html', context)


def report(request, pk):
    report = get_object_or_404(Report, pk=pk)
    return render(request, 'blog/report_detail.html', {'report': report})


def video_list(request):
    videos = Video.objects.all()
    videos = paginate(request, videos, 12)
    context = {
        'videos': videos,
    }
    return render(request, 'blog/video_list.html', context)


def video_detail(request, pk):
    video = Video.objects.get(pk=pk)
    comment = comments(request, pk, video, 'video')
    context = {
        'comment': comment[0],
        'form': comment[1],
        'video': comment[2],
        'show': comment[3],
    }
    return render(request, 'blog/video_detail.html', context)


def submitted_list(request):
    submitted = Submitted.objects.all()
    submitted = paginate(request, submitted, 12)
    context = {
        'submitted': submitted
    }
    return render(request, 'blog/submitted_list.html', context)


def submitted_detail(request, pk):
    submitted = get_object_or_404(Submitted, pk=pk)
    context = {
        'submitted': submitted
    }
    return render(request, 'blog/submitted_detail.html', context)


def not_found(request, exception):
    return render(request, 'blog/404.html')

blog/templates/blog/about.html
{% extends 'parent/base.html' %}
{% block title %}About{% endblock title %}
{% block content %}
    <div class="footer-box contact-box" style="text-align: center; background-color: snow; padding-bottom: 130px">

        {% for resm in resume %}
            <h1>{{ resm.title }}</h1>
   	    <img src="{{ resm.image1 }}">
            {% if resm.image2 %}
            	<img src="{{ resm.image2.url }}">
            {% endif %} 
   {% endfor %}
    </div>
{% endblock content %}

blog/templates/blog/article.html
{% extends 'parent/base.html' %}
{% block title %}Aticle{% endblock title %}
{% block content %}
    <div class="latest-posts">
        <div class="container-fluid">
            <div class="blog-title-span">
                <span class="title">اخبار و مقالات</span>
            </div>
            {% for post in posts %}
                <div class="col-md-3">
                    <div class="post-box">
                        <a href="{{ post.get_absolute_url }}">
                            <figure>
                                <img src="{{ post.image.url }}" alt="">
                                <figcaption class="meta-fig">
                                    <span><i class="fa fa-comment-o"></i> 12</span>
                                    <span><i class="fa fa-clock-o"></i>{{ post.created }}</span>&nbsp;

                                </figcaption>
                                <figcaption class="view">
                                    <span>{{ post.category }}</span>

                                </figcaption>
                            </figure>
                            <div class="text-p">
                                <h5>{{ post.title }}</h5>
                                <p>{{ post.content }}</p>
                                <div class="text-rigt">
                                    <a href="#">ادامه ...</a></div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}



            <div>{% include 'partials/pagination.html' with page=posts%}</div>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/contact_us.html
{% extends 'parent/base.html' %}
{% block title %}Contact_US{% endblock title %}
{% block content %}
<div class="footer-box contact-box" style="text-align: center; background-color: snow; padding-bottom: 130px">
                <span class="title" style="color: orange">تماس با ما</span>
    <br>
    <br>
                <p><i class="fa fa-phone"></i> 09198392998</p>
    <br>

    <p><i class="fa fa-phone"></i> 09389660893</p>
    <br>
                <p><i class="fa fa-envelope-o"></i> amirmahid.dehghani313@gmail.com</p>
    <br>
                <p><i class="fa fa-map-marker"></i> تهران </p>
            </div>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
    <div class="clear-fix"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="top-sidebar-r">
                    <span class="title"><a href="{% url 'blog:photo_list' %}">عکس</a></span>
                    {% for photo in photos %}
                        <a href="{{ photo.get_absolute_url }}">
                            <div class="bx">
                                <div class="col-md-6">
                                    <div class="img-box">
                                        <figure>
                                            <img src="{{ photo.image1 }}" alt="">
                                            <figcaption><span>1</span></figcaption>
                                        </figure>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="meta">
                                        <h5> {{ photo.content }}</h5>
                                        <span><i class="fa fa-clock-o"></i> {{ photo.created }}</span>
                                        <div class="text-left">
                                            <sub><i class="fa fa-comment"></i>{{ photo.comments.count }}</sub>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="main-slider-box">
                    <div class="owl-carousel owl-theme main-slider">
                        {% for hot in hots %}
                            <div class="item">
                                <figure>
                                    <img src="{{ hot.image }}" alt="">
                                    <figcaption class="gradient-fig"></figcaption>
                                    <figcaption class="desc-fig">
                                        <span><i class="fa fa-heart"></i> 56</span>
                                        <h3>{{ hot.title }}</h3>
                                        <span><i class="fa fa-clock-o"></i>{{ hot.created }}</span>
                                        <p>{{ hot.content }}
                                        </p>
                                    </figcaption>
                                </figure>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="top-sidebar-l">
                    <span class="title"> <a href="{% url 'blog:note_list' %}">یادداشت</a></span>
                    {% for note in notes %}

                        <div class="bx">
                            <div class="col-md-3 nopadding">
                                <a id="like-button"><span><i class="fa fa-heart"></i> {{ note.likes }}</span>
                                </a>
                            </div>
                            <a href="{{ note.get_absolute_url }}">
                                <div class="col-md-8 nopadding">
                                    <h3>{{ note.note }}</h3>
                                </div>
                            </a>
                        </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="clear-fix"></div>
    <div class="main-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <div class="r-sidebar">
                        <div class="special-posts">
                            <a href="{% url 'blog:submitted_list' %}"><span class="title">گفتگو</span><br></a>
                            {% for sub in submitted %}
                                <div class="special-box">
                                    <a href="{{ sub.get_absolute_url }}">
                                        <figure>
                                            <img src="{{ sub.image }}" alt="">
                                            <figcaption class="txt">
                                                <h4>{{ sub.title }}</h4>
                                                <span><i class="fa fa-comment-o"></i>{{ sub.comments.count }}</span>
                                                <span><i class="fa fa-calendar-o"></i> {{ sub.created }}</span>

                                            </figcaption>
                                            <figcaption class="link"><i class="fa fa-external-link"></i></figcaption>
                                        </figure>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>


                        <div class="ads-box">
                            <span class="title">تبلیغات</span><br>
                            {% for adv in advertising %}
                                <figure>
                                    <img src="{{ adv.video.url }}" alt="">
                                </figure>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="content-wrapper">
                        <div class="most-views">
                            <span class="title">مطالب پربازدید</span>
                            <div class="col-md-8" style="padding-left: 250px">
                                <div class="main-post">
                                    <a href="{{ view_day.get_absolute_url }}">
                                        <figure>
                                            <img src="{{ view_day.image.url }}" alt="">
                                            <figcaption>
                                                <span><i class="fa fa-folder-o"></i> خبر روز</span>
                                                <h3>{{ view_day.title }}</h3>
                                                <span><i
                                                        class="fa fa-comments-o"></i> {{ view_day.comments.count }}</span>
                                            </figcaption>
                                        </figure>
                                        <div class="p-div">
                                            <p>{{ view_day.content }}
                                            </p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="oth-posts">
                                    {% for viw in view_up %}
                                        <div class="r-box">
                                            <span class="cat-span">{{ viw.category }}</span>
                                            <a href="{{ viw.get_absolute_url }}">
                                                <h5>{{ viw.content }}</h5>
                                            </a>
                                            <span><i class="fa fa-clock-o"></i>{{ viw.created }}</span>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="special-cat-box">
                            <a href="{% url 'blog:video_list' %}"> <span class="title">فیلم و ویدئو</span></a>
                            <div class="col-md-6">
                                {% for vi1 in video2 %}
                                    <div class="main-post">
                                        <a href="{{ vi1.get_absolute_url }}">
                                            <figure>
                                                <img src="{{ vi1.image.url }}" alt="">
                                                <figcaption>
                                                    <span><i class="fa fa-folder-o"></i> خبر روز</span>
                                                    <h3>{{ vi1.title }}</h3>
                                                    <span><i
                                                            class="fa fa-comments-o"></i> {{ vi1.comments.count }}</span>
                                                </figcaption>
                                            </figure>
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-6">
                                <div class="left-content">
                                    {% for vid in video.exclude %}
                                        <div class="col-md-6">
                                            <a href="{{ vid.get_absolute_url }}">
                                                <div class="content">
                                                    <figure>
                                                        <img src="{{ vid.image.url }}" alt="">
                                                        <figcaption><i class="fa fa-external-link"></i></figcaption>
                                                    </figure>
                                                    <span>{{ vid.category }}</span>
                                                    <h5> متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت</h5>
                                                </div>
                                            </a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="l-sidebar">
                        <div class="cat-sidebar report">
                            <a href="{% url 'blog:report_list' %}"><span class="title">گزارش</span></a>
                            <div class="text-left"><i class="fa fa-arrows-alt"></i></div>
                            <ul>
                                {% for rep in report %}
                                    <li><a href="{{ rep.get_absolute_url }}">{{ rep.content }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="l-sidebar">
                        <div class="cat-sidebar">
                            <a href="{% url 'blog:article' %}"><span class="title">دسته بندی مطالب</span></a>
                            <div class="text-left"><i class="fa fa-folder-o"></i></div>
                            <ul>
                                {% for cat in categories %}
                                    <li>
                                        <a href="{{ cat.get_absolute_url }}">{{ cat }}</a><span>{{ cat.posts.count }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear-fix"></div>
        <div class="latest-posts">
            <div class="container-fluid">
                <div class="blog-title-span">
                    <span class="title">آخرین مطالب</span>
                </div>
                {% for post in posts %}
                    <div class="col-md-3">
                        <div class="post-box">
                            <a href="{{ post.get_absolute_url }}">
                                <figure>
                                    <img src="{{ post.image.url }}" alt="">
                                    <figcaption class="meta-fig">
                                        <span><i class="fa fa-comment-o"></i>{{ post.comments.count }}</span>
                                        <span><i class="fa fa-clock-o"></i>{{ post.created }}</span>&nbsp;

                                    </figcaption>
                                    <figcaption class="view">
                                        <span>{{ post.category }}</span>
                                    </figcaption>
                                </figure>
                                <div class="text-p">
                                    <h5>{{ post.title }}</h5>
                                    <p>{{ post.content }}
                                    </p>
                                    <div class="text-rigt">
                                        <a href="{{ post.get_absolute_url }}">ادامه ...</a></div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}